default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admetric_development

test:
  <<: *default
  database: admetric_test

production:
  <<: *default
  url: <%= ENV['MAIN_DATABASE_URL'] %>
